
version: '3.8'

services:
  discord-mcp-hub:
    build: .
    ports:
      - "8080:8080"
      - "5555:5555"
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - ZMQ_ADDRESS=tcp://0.0.0.0
      - ZMQ_PORT=5555
      - GIN_MODE=release
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge