package kbx

import "reflect"

type objectsInfo struct {
	TypeName     string
	Kind         reflect.Kind
	IsParsable   bool
	IsNullable   bool
	IsAcceptable bool
	IsExecutable bool
}

var (
	validKindMap = map[string]objectsInfo{
		reflect.Interface.String(): {
			TypeName:     reflect.Interface.String(),
			Kind:         reflect.Interface,
			IsParsable:   false,
			IsNullable:   true,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Struct.String(): {
			TypeName:     reflect.Struct.String(),
			Kind:         reflect.Struct,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Map.String(): {
			TypeName:     reflect.Map.String(),
			Kind:         reflect.Map,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Slice.String(): {
			TypeName:     reflect.Slice.String(),
			Kind:         reflect.Slice,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Array.String(): {
			TypeName:     reflect.Array.String(),
			Kind:         reflect.Array,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Chan.String(): {
			TypeName:     reflect.Chan.String(),
			Kind:         reflect.Chan,
			IsParsable:   false,
			IsNullable:   true,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Interface.String(): {
			TypeName:     reflect.Interface.String(),
			Kind:         reflect.Interface,
			IsParsable:   false,
			IsNullable:   true,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Ptr.String(): {
			TypeName:     reflect.Ptr.String(),
			Kind:         reflect.Ptr,
			IsParsable:   false,
			IsNullable:   true,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.String.String(): {
			TypeName:     reflect.String.String(),
			Kind:         reflect.String,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Bool.String(): {
			TypeName:     reflect.Bool.String(),
			Kind:         reflect.Bool,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},

		reflect.Int.String(): {
			TypeName:     reflect.Int.String(),
			Kind:         reflect.Int,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Uint.String(): {
			TypeName:     reflect.Uint.String(),
			Kind:         reflect.Uint,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Uint8.String(): {
			TypeName:     reflect.Uint8.String(),
			Kind:         reflect.Uint8,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Uint16.String(): {
			TypeName:     reflect.Uint16.String(),
			Kind:         reflect.Uint16,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Uint32.String(): {
			TypeName:     reflect.Uint32.String(),
			Kind:         reflect.Uint32,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Uint64.String(): {
			TypeName:     reflect.Uint64.String(),
			Kind:         reflect.Uint64,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Int8.String(): {
			TypeName:     reflect.Int8.String(),
			Kind:         reflect.Int8,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Int16.String(): {
			TypeName:     reflect.Int16.String(),
			Kind:         reflect.Int16,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Int32.String(): {
			TypeName:     reflect.Int32.String(),
			Kind:         reflect.Int32,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Int64.String(): {
			TypeName:     reflect.Int64.String(),
			Kind:         reflect.Int64,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Float32.String(): {
			TypeName:     reflect.Float32.String(),
			Kind:         reflect.Float32,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Float64.String(): {
			TypeName:     reflect.Float64.String(),
			Kind:         reflect.Float64,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},

		reflect.Map.String(): {
			TypeName:     reflect.Map.String(),
			Kind:         reflect.Map,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Slice.String(): {
			TypeName:     reflect.Slice.String(),
			Kind:         reflect.Slice,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Array.String(): {
			TypeName:     reflect.Array.String(),
			Kind:         reflect.Array,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Chan.String(): {
			TypeName:     reflect.Chan.String(),
			Kind:         reflect.Chan,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},

		reflect.Func.String(): {
			TypeName:     reflect.Func.String(),
			Kind:         reflect.Func,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Uintptr.String(): {
			TypeName:     reflect.Uintptr.String(),
			Kind:         reflect.Uintptr,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Complex64.String(): {
			TypeName:     reflect.Complex64.String(),
			Kind:         reflect.Complex64,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
		reflect.Complex128.String(): {
			TypeName:     reflect.Complex128.String(),
			Kind:         reflect.Complex128,
			IsParsable:   true,
			IsNullable:   false,
			IsAcceptable: true,
			IsExecutable: false,
		},
	}
)
